### ISSUE TITLE
fix api blog error

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-main#253]
see https://github.com/cmu-delphi/www-main/runs/2040846791?check_suite_focus=true

**Comment by sgratzl** [comment]
I assume it is because:

> Fetching covid_ag_raw_pct_positive from quidel for 2020-08-01 to 2020-08-01 in geography 'ny': no results 

@krivard can you update the code to work again?

**Comment by krivard** [comment]
This is probably due to BIGINT -- the only issues we have for 2020 are the latest issue for each day, so if that falls outside of the queried range it won't return anything.

We're still looking for a way to restore the 2020 data history that doesn't require taking down COVIDcast for 2 days and will complete before May.

**Comment by sgratzl** [comment]
are there any workaround in which we could change the blog post? it is getting annoying that half my CI build fail
