### ISSUE TITLE
Center of Excellence page

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-main#32]
Implement the redesigned center-of-excellence page

**Comment by sgratzl** [comment]
what is the status here, so far it is just very briefly mentioned?

**Comment by tildechris** [comment]
@Letsgohyde , I think we pushed this to the next release, no?

**Comment by sgratzl** [comment]
from https://github.com/cmu-delphi/www-main/pull/193#issuecomment-821720050:


hey guys, I updated the design based on Roni's feedback. 
![DELPHI_Center-of-Excel-page_v1 (1)](https://user-images.githubusercontent.com/7318770/115093610-c70f0000-9ecf-11eb-8177-9ab309cfdbcd.png)

https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2843%3A224

**Comment by sgratzl** [comment]
from https://github.com/cmu-delphi/www-main/pull/193#issuecomment-821724379

Tablet design: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2843%3A770
Mobile design: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2843%3A305

![DELPHI_Center-of-Excel-page_v1 (2)](https://user-images.githubusercontent.com/7318770/115094426-50273680-9ed2-11eb-94f3-7d42675610cf.png)

**Comment by sgratzl** [comment]
https://github.com/cmu-delphi/www-main/pull/193#issuecomment-821745435

Thanks Raph!  This looks very nice!

Just a few small tweaks left:

  *   The second paragraph in the “About the Center” box should be eliminated.
  *   The “Special thanks to CDC” at the very bottom should be bigger / more salient than the list of supporters above it.
  *   “Harvard College” should be changed to “Harvard University”
  *   “UHG / Optum” should be changed to “UnitedHealth / Optum”  (note the lack of space between “United” and “Health”)
  *   CDC does not allow the use of its logo.  One way we finessed it is by inventing our own 😉  :  instead of a logo, we used a logo-like square or circle with big bold black-and-white “US CDC” in it.  You may have seen it in an older version of our website.
  *   I don’t know whether U Mass allows the use of their logo.  Regardless, I think it might be more appropriate to use the Forecast Hub<https://covid19forecasthub.org/> logo or the Reich’s lab<https://reichlab.io/> logo instead – I am sure Nick will be fine with that.

**Comment by sgratzl** [comment]
updated PR in #292

**Comment by Letsgohyde** [comment]
Awesome! I just updated the figma file. https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2843%3A224
![DELPHI_Center-of-Excel-page_v1 (3)](https://user-images.githubusercontent.com/7318770/115320294-75b47a00-a136-11eb-8a04-78ca8f3ea292.png)

The desktop design has the updated content, while the mobile versions are just updated with the proper formatting.
