### ISSUE TITLE
grayscale vs color in landing page

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-main#86]
in the landing page we have a grayscale next to a color image which looks a bit weird to me. is there a specific design reason?

![image](https://user-images.githubusercontent.com/4129778/99969019-e57d2f00-2d67-11eb-990d-9377e169df2a.png)

**Comment by jennyxxdance** [comment]
Hm, I agree but Raph and I changed the team photo in black and white on purpose because everyone's headshots seemed to have very different color and contrast, so to minimize the varying gap, we muted all the colors by making it B&W. And the image for the API on the right, we used unsplash.com to find free licensed stock image. Do you think we should replace it with a black and white image for API, or put team photo back to its original colors?

**Comment by jennyxxdance** [comment]
@Letsgohyde @tildechris What do you think?

**Comment by tildechris** [comment]
I think it's OK for now.  In the future, I'd like to use a dynamic component for the team images so we can show more people.  Let's revisit this in the future.
